### PR TITLE
wharf-api gRPC client

### PR DESCRIPTION
**Pull request by jilleJr**
- \[x] I've added a new note in the `CHANGELOG.md` file, according to docs:
  https://iver-wharf.github.io/#/development/changelogs/writing-changelogs
- \[x] Wait for #36 to be merged, as I'm depending on Go 1.17 code with `math.MaxUint`
- \[x] Wait for https://github.com/iver-wharf/wharf-api/pull/147 to be merged.

## Summary

- Copied protobuf def from wharf-api, but changed the `go_package`
- Added gRPC client implementation

## Motivation

Adds support to talk to wharf-api's newly introduced gRPC API since v5.1.0.

I decided to create a new gRPC client on a per-request basis. This should maybe change but that would need to be added into the `wharfapi.Client` type, best done via a constructor. Or we could use the `wharfapi.Client` just for caching the gRPC client.

Nothing I don't see we can improve on later. We could easily add that in later if we find it a challenge, such as if we add other RPCs that would really benefit from being multiplexed.

### CODE REVIEW

**Comment by Alexamakans** [comment]
LGTM 👍🏻

**Comment by jilleJr** [comment]
> LGTM 👍🏻

Sorry didn't notice you reviewed already. I rebased off of `master` after #36 was merged and did an additional `go mod tidy`.

**Review by Alexamakans — APPROVED** [review]
Still LGTM ;) 👍🏻

Would be nice to have the "codacy ignore *.pb.go files" change here as well.

**Comment by jilleJr** [comment]
> Would be nice to have the "codacy ignore *.pb.go files" change here as well.

Good note! Added

**Pull request merged**
