### PR TITLE
Moved linting to Makefile

### PR DESCRIPTION
**Pull request by jilleJr**
## Summary

- Added targets to `Makefile` for linting and other utilities like cleaning
- Removed linting from NPM scripts in `package.json`
- Simplified linting docs

## Motivation

Moves focus from relying on NPM for all linting stuff over to Makefile.

Based on https://github.com/iver-wharf/wharf-cmd/pull/31

### CODE REVIEW

**Review by Alexamakans — APPROVED** [review]

**Review by fredx30 — APPROVED** [review]
This could probably use some extra testing. As far as the moving of the linting goes this is ok. 

When i try using the lint check however the linting does not fix issues i would expect it to. I assume this is a config error however.
See this chain of commands
First i create 2 diffs, one missing space at the start of a comment, and a missing space in a function defining curly bracket. Then i run the linter, then i check if the linting normalised the style- It did not.

```pwsh
C:\Users\fred\Wharf\wharf-api-client-go [feature/makefile-linting ≡ +0 ~1 -0 !]> git diff
diff --git a/pkg/wharfapi/client.go b/pkg/wharfapi/client.go
index f2d281f..d3d4201 100644
--- a/pkg/wharfapi/client.go
+++ b/pkg/wharfapi/client.go
@@ -10,13 +10,13 @@ import (
 // AuthError is returned on authentication/authorization errors issued when
 // trying to communicate with the Wharf API.
 //
-// This could be because of missing, invalid, or outdated authentication header
+//This could be because of missing, invalid, or outdated authentication header
 // provided to the client.
 type AuthError struct {
        Realm string
 }

-func (e *AuthError) Error() string {
+func (e *AuthError) Error() string{
        return e.Realm
 }

C:\Users\fred\Wharf\wharf-api-client-go [feature/makefile-linting ≡ +0 ~1 -0 !]> make lint-go
revive -formatter stylish -config revive.toml ./...
C:\Users\fred\Wharf\wharf-api-client-go [feature/makefile-linting ≡ +0 ~1 -0 !]> git diff
diff --git a/pkg/wharfapi/client.go b/pkg/wharfapi/client.go
index f2d281f..d3d4201 100644
--- a/pkg/wharfapi/client.go
+++ b/pkg/wharfapi/client.go
@@ -10,13 +10,13 @@ import (
 // AuthError is returned on authentication/authorization errors issued when
 // trying to communicate with the Wharf API.
 //
-// This could be because of missing, invalid, or outdated authentication header
+//This could be because of missing, invalid, or outdated authentication header
 // provided to the client.
 type AuthError struct {
        Realm string
 }

-func (e *AuthError) Error() string {
+func (e *AuthError) Error() string{
        return e.Realm
 }
```

**Comment by jilleJr** [comment]
> This could probably use some extra testing. As far as the moving of the linting goes this is ok.
> 
> When i try using the lint check however the linting does not fix issues i would expect it to. I assume this is a config error however. See this chain of commands First i create 2 diffs, one missing space at the start of a comment, and a missing space in a function defining curly bracket. Then i run the linter, then i check if the linting normalised the style- It did not.
> 
> ```powershell
> ## snip
> ```

Ah yes well the `make lint-go` does not run the `goimports`. The `revive` command that it runs performs linting issues such as unused parameters.

I've updated the Makefile to use goimports in lint-go and the new lint-go-fix. If you approve then I will apply the same on the other similar PRs for our Go repos

**Comment by jilleJr** [comment]
Sample usage:

```console
$ git diff
diff --git a/pkg/wharfapi/client.go b/pkg/wharfapi/client.go
index f2d281f..7491f75 100644
--- a/pkg/wharfapi/client.go
+++ b/pkg/wharfapi/client.go
@@ -16,7 +16,7 @@ type AuthError struct {
 	Realm string
 }

-func (e *AuthError) Error() string {
+func (e *AuthError) Error()string {
 	return e.Realm
 }


$ make lint-go-fix
goimports -d -w pkg/model/request/request.go pkg/model/response/response.go pkg/wharfapi/artifact.go pkg/wharfapi/branch.go pkg/wharfapi/build.go pkg/wharfapi/buildstatus.go pkg/wharfapi/client.go pkg/wharfapi/doc.go pkg/wharfapi/logger.go pkg/wharfapi/project.go pkg/wharfapi/provider.go pkg/wharfapi/requestHandler.go pkg/wharfapi/requestHandler_test.go pkg/wharfapi/test_result.go pkg/wharfapi/token.go pkg/wharfapi/util.go pkg/wharfapi/util_test.go
diff -u pkg/wharfapi/client.go.orig pkg/wharfapi/client.go
--- pkg/wharfapi/client.go.orig	2022-02-09 16:08:22.014860551 +0100
+++ pkg/wharfapi/client.go	2022-02-09 16:08:22.014860551 +0100
@@ -16,7 +16,7 @@
 	Realm string
 }

-func (e *AuthError) Error()string {
+func (e *AuthError) Error() string {
 	return e.Realm
 }


$ git diff

$
```

**Comment by fredx30** [comment]
👍 I think that covers the scope for this PR. 

For me it still not autofixing the first character as space in single line comments. It might be more related to specific settings though- at the same time i know i always miss it unless i run my ide formatting rules which have a preset surplus to the ones set by this project. The space first comments have no exceptions in this code so im assuming its a rule but it does not seem to be set by the linting as is here.

**Comment by jilleJr** [comment]
Yea well I mean only a madman would omit that space 😉

And no, goimports/gofmt does not seem to fix that, and neither supports any sort of configs. It's very opinionated, although not enough in this case.

**Review by Alexamakans — APPROVED** [review]

**Pull request merged**
